# @package _global_

defaults:
  - _self_
  - data: null
  - callbacks: default
  - model: default
  - logger: null
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

  # allow experiment configs (carry architecture overrides) to compose in eval too
  - experiment: null

trainer:
  accelerator: gpu
  devices: [0]

task_name: null

tags: []

ckpt_path: null
